export const PersonalAreaConsultationIsCalendarKey = 'PersonalAreaConsultationIsCalendar';
export const PersonalAreaConsultationIsCalendarSpecialistKey = 'PersonalAreaConsultationIsCalendarSpecialistKey';
export const PersonalAreaConsultationSpecialistFilterKey = 'PersonalAreaConsultationSpecialistFilterKey';
